id: PDFEA73E3
initial_creation_type: input
source_metadata:
  title: Shechen Rabjam Rinpoche Series
  language: pt
  description: 'Texts by and about Jigme Chökyi Senge (''jigs med chos kyi seng+ge,
    b. 1966), the seventh Rabjam Rinpoche of Shechen Monastery:'
  volume:
    4de8122272c94df38faaceec9b7e145a:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    517c805e7f074591adbb9cc3256b37ce:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Long Life Prayers
    6518cd9ac03d404b8e4ab243f75ac30c:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    5937911b4eb84cf98ed09424dab43a7f:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    810ef4a3f68a458393c47e75d81aa23d:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Prayers
    02cc6e01d80145d783bd738611bd199c:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    1b60c50f90e1430e8e4c2ef6037f19b1:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    494bc01e9de740879ffbb2554a175907:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:35:58.834394'
last_modified_at: '2022-03-01T01:35:58.834397'
